global:
  namespace: "kafka"

producer:
  image: longbale1999/webhook-producer:1.1.1
  replicaCount: 1
  port: 8084

notifier:
  replicaCount: 1
  image: longbale1999/webhook-notifier:1.3.0
  service:
    type: ClusterIP
    port: 8080
  env:
    # Kafka Config
    BOOTSTRAP_SERVERS_CONFIG: "my-cluster-kafka-bootstrap:9092"
    WEBHOOK_EVENT_TOPIC: "webhook-events"
    WEBHOOK_EVENT_TOPIC_PARTITIONS: 3
    WEBHOOK_EVENT_TOPIC_REPLICATION_FACTOR: 1
    WEBHOOK_EVENT_DEAD_LETTER_QUEUE_TOPIC: "webhook-event-dead-letter-queue"
    WEBHOOK_EVENT_DEAD_LETTER_QUEUE_TOPIC_PARTITIONS: 3
    WEBHOOK_EVENT_DEAD_LETTER_QUEUE_TOPIC_REPLICATION_FACTOR: 1
    # Database Config
    DB_HOST: "postgres"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    # Redis Config
    REDIS_HOST: "redis"
    REDIS_PORT: 6379
    LIMIT_EVENT_COUNT: 7500
    LIMIT_EVENT_DURATION: 1  # 1 minute
    # Resilience4j Circuit Breaker Config
    WEBHOOK_RETRY_MAX_ATTEMPTS: 5
    WEBHOOK_RETRY_WAIT_DURATION: "2s"
    WEBHOOK_CIRCUIT_FAILURE_THRESHOLD: 50
    WEBHOOK_CIRCUIT_SLOW_RATE_THRESHOLD: 60
    WEBHOOK_CIRCUIT_SLOW_DURATION_THRESHOLD: "2s"
    WEBHOOK_CIRCUIT_WAIT_OPEN_STATE: "10s"
    WEBHOOK_CIRCUIT_PERMITTED_CALLS_HALF_OPEN: 3
    WEBHOOK_CIRCUIT_MIN_CALLS: 5
    WEBHOOK_CIRCUIT_EVENT_BUFFER_SIZE: 10
    # Thread Pool Config
    KAFKA_CONSUMER_CORE_SIZE: 10
    KAFKA_CONSUMER_MAX_SIZE: 50
    KAFKA_CONSUMER_QUEUE_CAPACITY: 100

dlq:
  replicaCount: 1
  image: longbale1999/webhook-dlq-service:1.0.2
  service:
    type: ClusterIP
    port: 8088
  env:
    # Kafka Config
    BOOTSTRAP_SERVERS_CONFIG: "my-cluster-kafka-bootstrap:9092"
    WEBHOOK_EVENT_TOPIC: "webhook-events"
    WEBHOOK_EVENT_TOPIC_PARTITIONS: 3
    WEBHOOK_EVENT_TOPIC_REPLICATION_FACTOR: 1
    WEBHOOK_EVENT_DEAD_LETTER_QUEUE_TOPIC: "webhook-event-dead-letter-queue"
    WEBHOOK_EVENT_DEAD_LETTER_QUEUE_TOPIC_PARTITIONS: 3
    WEBHOOK_EVENT_DEAD_LETTER_QUEUE_TOPIC_REPLICATION_FACTOR: 1
    # Database Config
    DB_HOST: "postgres"
    DB_NAME: "webhook"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    # Thread Pool Config
    KAFKA_CONSUMER_CORE_SIZE: 10
    KAFKA_CONSUMER_MAX_SIZE: 50
    KAFKA_CONSUMER_QUEUE_CAPACITY: 100

postgres:
  image: "postgres:latest"
  storage: 10Gi
  port: 5432
  nodePort: 30432
  username: "postgres"
  password: "postgres"
  database: "webhook"

redis:
  image: "redis:latest"
  storage: 5Gi
  port: 6379
  usePassword: false  # Set to false for local/staging
  password: "strongpassword"

prometheus:
  image: "prom/prometheus:latest"
  port: 9090

grafana:
  image: "grafana/grafana:latest"
  port: 3000

ingress:
  host:
    producer: "producer.test"
    dlq: "dlq.test"
