# 'values.yaml' contains default values for all your templates.
authDb:
  image: mysql:8                     # MySQL image to use for auth-db service
  replicaCount: 1                     # Number of replicas for auth-db deployment
  storage: 2Gi                        # Persistent volume size for auth-db
  rootPassword: password              # Root password for the database
  dbName: authdb                      # Name of the database for auth service
  username: authuser                  # Username for the auth database
  password: authpassword              # Password for the auth database

customerDb:
  image: mysql:8                     # MySQL image to use for customer-db service
  replicaCount: 1                     # Number of replicas for customer-db deployment
  storage: 2Gi                        # Persistent volume size for customer-db
  rootPassword: password              # Root password for the database
  dbName: customerdb                  # Name of the database for customer management service
  username: customeruser              # Username for the customer database
  password: customerpassword          # Password for the customer database

redis:
  image: redis:6.2.6                  # Redis image to use for Redis service
  replicaCount: 1                     # Number of replicas for Redis deployment
  storage: 2Gi                        # Persistent volume size for Redis
  password: password                  # Password for Redis

authService:
  image: longbale1999/auth-service:1.0.0  # Docker image for the Auth service
  replicaCount: 2                     # Number of replicas for auth-service deployment
  port: 8080                          # Container port for the Auth service
  dbUrl: jdbc:mysql://auth-db:3306/authdb  # URL to connect to the auth-db database
  dbUsername: authuser                # Username to connect to the auth-db database
  dbPassword: authpassword            # Password to connect to the auth-db database
  redisHost: redis                    # Redis host
  redisPort: 6379                     # Redis port
  awsAccessKeyId:  # AWS access key ID
  awsSecretAccessKey:

customerService:
  image: longbale1999/customer-management-service:1.0.0  # Docker image for the customer management service
  replicaCount: 2                     # Number of replicas for customer management service deployment
  port: 8080                          # Container port for customer management service
  dbUrl: jdbc:mysql://customer-management-db:3306/customerdb  # URL to connect to the customer-db database
  dbUsername: customeruser            # Username to connect to the customer-db database
  dbPassword: customerpassword        # Password to connect to the customer-db database
  redisHost: redis                    # Redis host
  redisPort: 6379                     # Redis port
