apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: {{ .Values.authService.replicaCount }}  # Number of replicas (from values.yaml)
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: auth-service
          image: {{ .Values.authService.image }}  # Docker image (from values.yaml)
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.authService.dbUrl }}  # Database URL (from values.yaml)
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.authService.dbUsername }}  # Database username (from values.yaml)
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.authService.dbPassword }}  # Database password (from values.yaml)
            - name: REDIS_HOST
              value: {{ .Values.authService.redisHost }}  # Redis host (from values.yaml)
            - name: REDIS_PORT
              value: "{{ .Values.authService.redisPort }}"  # Redis port (from values.yaml)
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.authService.awsAccessKeyId }}  # AWS access key ID (from values.yaml)
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.authService.awsSecretAccessKey }}  # AWS secret access key (from values.yaml)
