apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-db
spec:
  replicas: {{ .Values.customerDb.replicaCount }}  # Number of replicas (from values.yaml)
  selector:
    matchLabels:
      app: customer-management-db
  template:
    metadata:
      labels:
        app: customer-management-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mysql
          image: {{ .Values.customerDb.image }}  # MySQL image (from values.yaml)
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.customerDb.rootPassword }}  # Root password for MySQL (from values.yaml)
            - name: MYSQL_DATABASE
              value: {{ .Values.customerDb.dbName }}  # Database name for MySQL (from values.yaml)
            - name: MYSQL_USER
              value: {{ .Values.customerDb.username }}  # Database username (from values.yaml)
            - name: MYSQL_PASSWORD
              value: {{ .Values.customerDb.password }}  # Database password (from values.yaml)
