apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}  # Number of Redis replicas (from values.yaml)
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: {{ .Values.redis.image }}  # Redis image (from values.yaml)
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}  # Redis password (from values.yaml)
          volumeMounts:
            - name: redis-data
              mountPath: /data  # Mounting the persistent storage volume for Redis data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc  # PVC for persistent storage of Redis data

