apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Use NGINX ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2  # Rewrite target path for correct routing
spec:
  rules:
    - host: microservice.test  # Local domain for testing
      http:
        paths:
          - path: /auth/api/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service  # Route to the auth-service
                port:
                  number: 80
          - path: /customer/api/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: customer-management-service  # Route to the customer-management-service
                port:
                  number: 80
