apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  annotations:
    argocd.argoproj.io/ignore: "true"
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql
