apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # Encode all sensitive information (passwords) in base64 for security.
  auth-db-rootpassword: {{ .Values.authDb.rootPassword | b64enc | quote }}
  auth-db-password: {{ .Values.authDb.password | b64enc | quote }}
  customer-db-rootpassword: {{ .Values.customerDb.rootPassword | b64enc | quote }}
  customer-db-password: {{ .Values.customerDb.password | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
