apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 80  # HTTP port for external access
      targetPort: 8080  # Container port for the service
