apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: {{ .Values.producer.image }}
          ports:
            - containerPort: {{ .Values.producer.port }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.notifier.env.BOOTSTRAP_SERVERS_CONFIG }}
            - name: WEBHOOK_EVENT_TOPIC
              value: {{ .Values.notifier.env.WEBHOOK_EVENT_TOPIC }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.producer.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.producer.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
