server:
  port: 8084

spring:
  application:
    name: event-producer
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    webhook-event-topic: ${WEBHOOK_EVENT_TOPIC:webhook-events}

management:
  endpoints:
    web:
      exposure:
        include: "*"