apiVersion: v1
kind: Service
metadata:
  name: dlq
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: dlq
  ports:
    - protocol: TCP
      port: {{ .Values.dlq.service.port }}
      targetPort: {{ .Values.dlq.service.port }}
