apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}
