apiVersion: v1
kind: Service
metadata:
  name: notifier
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: {{ .Values.notifier.port }}
      targetPort: {{ .Values.notifier.port }}
