apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: {{ .Values.producer.port }}
      targetPort: {{ .Values.producer.port }}
